inherited frmIncluirAlterarClientes: TfrmIncluirAlterarClientes
  ActiveControl = dbedtNome
  Caption = ''
  ClientHeight = 234
  ClientWidth = 617
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnShow = FormShow
  ExplicitWidth = 623
  ExplicitHeight = 262
  PixelsPerInch = 96
  TextHeight = 13
  object lbl1: TLabel
    Left = 10
    Top = 4
    Width = 34
    Height = 14
    Caption = 'Nome'
    FocusControl = dbedtNome
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object lbl2: TLabel
    Left = 10
    Top = 40
    Width = 29
    Height = 14
    Caption = 'Fone'
    FocusControl = dbedtFone
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object lbl3: TLabel
    Left = 204
    Top = 40
    Width = 18
    Height = 14
    Caption = 'Cel'
    FocusControl = dbedtCel
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object lbl4: TLabel
    Left = 10
    Top = 79
    Width = 41
    Height = 14
    Caption = 'Cidade'
    FocusControl = dbedtCidade
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object lbl5: TLabel
    Left = 313
    Top = 79
    Width = 36
    Height = 14
    Caption = 'Bairro'
    FocusControl = dbedtBairro
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object lbl6: TLabel
    Left = 10
    Top = 116
    Width = 24
    Height = 14
    Caption = 'Rua'
    FocusControl = dbedtRua
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object lbl7: TLabel
    Left = 389
    Top = 40
    Width = 23
    Height = 14
    Caption = 'Cep'
    FocusControl = dbedtCep
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object lbl8: TLabel
    Left = 10
    Top = 154
    Width = 47
    Height = 14
    Caption = 'N'#250'mero'
    FocusControl = dbedtRua
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object lbl9: TLabel
    Left = 88
    Top = 154
    Width = 85
    Height = 14
    Caption = 'Complemento'
    FocusControl = dbedtRua
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object dbedtNome: TDBEdit
    Left = 10
    Top = 17
    Width = 487
    Height = 22
    DataField = 'nome'
    DataSource = dmPesqClientesVenda.dsIncluirAlterarClientes
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
  end
  object dbedtFone: TDBEdit
    Left = 10
    Top = 55
    Width = 134
    Height = 22
    DataField = 'fone'
    DataSource = dmPesqClientesVenda.dsIncluirAlterarClientes
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 1
    OnKeyPress = dbedtFoneKeyPress
  end
  object dbedtCel: TDBEdit
    Left = 204
    Top = 55
    Width = 134
    Height = 22
    DataField = 'cel'
    DataSource = dmPesqClientesVenda.dsIncluirAlterarClientes
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 2
    OnKeyPress = dbedtCelKeyPress
  end
  object dbedtCidade: TDBEdit
    Left = 10
    Top = 93
    Width = 295
    Height = 22
    DataField = 'cidade'
    DataSource = dmPesqClientesVenda.dsIncluirAlterarClientes
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 5
  end
  object dbedtBairro: TDBEdit
    Left = 313
    Top = 93
    Width = 293
    Height = 22
    DataField = 'bairro'
    DataSource = dmPesqClientesVenda.dsIncluirAlterarClientes
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 6
  end
  object dbedtRua: TDBEdit
    Left = 10
    Top = 131
    Width = 596
    Height = 22
    DataField = 'rua'
    DataSource = dmPesqClientesVenda.dsIncluirAlterarClientes
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 7
  end
  object dbedtCep: TDBEdit
    Left = 389
    Top = 55
    Width = 171
    Height = 22
    Hint = 'Para o CEP ser v'#225'lido tem que ter (8)digitos.'
    DataField = 'cep'
    DataSource = dmPesqClientesVenda.dsIncluirAlterarClientes
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold, fsItalic]
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 3
    OnKeyPress = dbedtCepKeyPress
  end
  object dbedtNum: TDBEdit
    Left = 10
    Top = 169
    Width = 72
    Height = 22
    DataField = 'numero'
    DataSource = dmPesqClientesVenda.dsIncluirAlterarClientes
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 8
  end
  object dbedtComplemento: TDBEdit
    Left = 88
    Top = 169
    Width = 250
    Height = 22
    DataField = 'complemento'
    DataSource = dmPesqClientesVenda.dsIncluirAlterarClientes
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 9
  end
  object edtComplemento2: TEdit
    Left = 344
    Top = 169
    Width = 262
    Height = 22
    TabStop = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clRed
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    ReadOnly = True
    TabOrder = 10
    TextHint = 'Complemento busca CEP.'
  end
  object btnCep: TBitBtn
    Left = 563
    Top = 55
    Width = 43
    Height = 22
    Caption = 'CEP'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clGreen
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold, fsItalic]
    ParentFont = False
    TabOrder = 4
    OnClick = btnCepClick
  end
  object btnSalvar: TButton
    Left = 534
    Top = 197
    Width = 75
    Height = 32
    Caption = 'Salvar'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 11
    OnClick = btnSalvarClick
  end
  object btnLimpar: TButton
    Left = 434
    Top = 197
    Width = 75
    Height = 32
    Caption = 'Limpar'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 12
    OnClick = btnLimparClick
  end
end
